import crypto from "crypto";

const superheroNames = [
    "Superman",
    "Batman",
    "Spiderman",
    "WonderWoman",
    "IronMan",
    "CaptainAmerica",
    "Hulk",
    "Thor",
    "Flash",
    "GreenLantern",
    "Aquaman",
    "Robin",
    "GreenArrow",
    "Cyborg",
    "Shazam",
    "BlackWidow",
    "Hawkeye",
    "DoctorStrange",
    "BlackPanther",
    "AntMan",
    "Wasp",
    "ScarletWitch",
    "Vision",
    "CaptainMarvel",
    "Supergirl",
    "Batgirl",
    "Nightwing",
    "Starfire",
    "Raven",
    "BeastBoy",
    "MartianManhunter",
    "Zatanna",
    "Constantine",
    "TheAtom",
    "BlueBeetle",
    "Hawkman",
    "Huntress",
    "PowerGirl",
    "Firestorm",
    "CaptainAtom",
    "AtomSmasher",
    "BlackLightning",
    "StaticShock",
    "Vixen",
    "RedHood",
    "Deadpool",
    "Wolverine",
    "Cyclops",
    "Storm",
    "JeanGrey",
    "Nightcrawler",
    "Colossus",
    "Gambit",
    "Rogue",
    "Cable",
    "Ben10",
    "Tom",
    "Jerry",
    "PowerRangers",
    "OptimusPrime",
    "Megatron",
    "Bumblebee",
    "Ratchet",
    "Jazz",
    "Ironhide",
    "Grimlock",
    "Starscream",
    "HotRod",
    "Ultron",
    "Mystique",
    "Jubilee",
    "KittyPryde"
];

export function aliasNamesGenerator() {
    const name = superheroNames[Math.floor(Math.random() * superheroNames.length)];
    // Generate a random suffix (4 hex characters = 2 bytes)
    const suffix = crypto.randomBytes(2).toString("hex");
    return `${name}_${suffix}`;
}
